import { WHITE_SERVICE_NAME } from './product'

export const STATUS_CODE = {
  WAIT_PAY: 'WAIT_PAY',
  WAIT_DELIVERY: 'WAIT_DELIVERY',
  WAIT_RECEIVE: 'WAIT_RECEIVE',
  WAIT_EVALUATE: 'WAIT_EVALUATE',
  COMPLETED: 'COMPLETED',
  CANCELED: 'CANCELED',
  AUTO_CANCEL: 'AUTO_CANCEL',
  PARTIAL_PAID: 'PARTIAL_PAID',
  PARTIAL_SHIPPED: 'PARTIAL_SHIPPED',
  PARTIAL_RECEIVED: 'PARTIAL_RECEIVED',
}

export const STATUS_TXT = {
  [STATUS_CODE.WAIT_PAY]: '待付款',
  [STATUS_CODE.WAIT_DELIVERY]: '支付完成',
  [STATUS_CODE.WAIT_RECEIVE]: '已发货',
  [STATUS_CODE.WAIT_EVALUATE]: '已发货',
  [STATUS_CODE.COMPLETED]: '已发货',
  [STATUS_CODE.AUTO_CANCEL]: '已取消',
  [STATUS_CODE.CANCELED]: '已取消',
  [STATUS_CODE.PARTIAL_PAID]: '支付完成',
  [STATUS_CODE.PARTIAL_SHIPPED]: '已发货',
  [STATUS_CODE.PARTIAL_RECEIVED]: '已发货',
}

// 表示已经支付的状态
export const ORDER_PAID = [
  STATUS_CODE.WAIT_DELIVERY,
  STATUS_CODE.WAIT_RECEIVE,
  STATUS_CODE.WAIT_EVALUATE,
  STATUS_CODE.COMPLETED,
  STATUS_CODE.PARTIAL_PAID,
  STATUS_CODE.PARTIAL_SHIPPED,
  STATUS_CODE.PARTIAL_RECEIVED]

export const CURRENCY_CODE = 'CNY'

export const PRODUCT_TYPE = {
  PRODUCT: 'SALABLE_PRODUCT', // 非赠品
  GIFT: 'GIFT', // 赠品
}

// 开票的类型  个人还是公司
export const INVOICE_TITLE_TYPE = {
  COMPANY: 'COMPANY',
  PERSONAL: 'PERSONAL',
}
// 邮寄方式
export const INVOICE_DISTRIBUTION_TYPE = 'EXPRESS'

// 电子发票
export const INVOICE_CARRIER = 'ELECTRONIC'

// 发票类型--普通发票
export const INVOICE_TYPE = 'PLAIN'

// 发票状态
export const INVOICE_STATUS = {
  SUCCESS: 'SUCCESS',
  PROGRESS: 'PROGRESS',
  EMPTY: 'EMPTY',
  FAILED: 'FAILED',
}

export const INVOICE_STATUS_TXT = {
  [INVOICE_STATUS.SUCCESS]: '电子发票已开，请查收邮箱',
  [INVOICE_STATUS.PROGRESS]: '已提交电子发票',
  [INVOICE_STATUS.EMPTY]: '申请电子发票',
  [INVOICE_STATUS.FAILED]: '',
}

export const TIMEOUT_AUTO_CANCELLED = {
  CODE: 'TIMEOUT_AUTO_CANCELLED',
  TXT: '支付超时',
}

// 可以查询物流的订单状态
export const QUERY_LOGISTICS_STATUS = [STATUS_CODE.WAIT_RECEIVE,
  STATUS_CODE.WAIT_EVALUATE, STATUS_CODE.COMPLETED, STATUS_CODE.PARTIAL_SHIPPED,
  STATUS_CODE.PARTIAL_RECEIVED]

// 白手套服务相关的数据
export const WHITE_GLOVE_SERVICE = {
  serviceType: 'WHITE_GLOVE_SERVICE',
  name: WHITE_SERVICE_NAME,
  amount: 0,
}
// sku property 分隔符
export const SKU_SPLIT = '|'
