export const USER_ACTION_SET_ID = '1111813002'

export const ACTION_TYPE = {
  COMPLETE_ORDER: 'COMPLETE_ORDER', // 下单
  RESERVATION: 'RESERVATION', // 预约
  CONFIRM_EFFECTIVE_LEADS: 'CONFIRM_EFFECTIVE_LEADS', // 确认有效销售线索
  PURCHASE: 'PURCHASE', // 付费销售线索
  REGISTER: 'REGISTER', // 注册
}
